# Checks for the presence of merge conflict markers.
# From: https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/.vale/gitlab/MergeConflictMarkers.yml
#
# For a list of all options, see https://errata-ai.gitbook.io/vale/getting-started/styles
extends: existence
message: 'Merge conflict marker "%s" found.'
link: https://docs.gitlab.com/ee/development/code_review.html#merging-a-merge-request
level: error
scope: raw
raw:
  - '\n<<<<<<< .+\n|\n=======\n|\n>>>>>>> .+\n'
